name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Test
        run: go test -vet "" -cover .
        

# go test -vet "" -cover -coverprofile cover.out . && \
# go tool cover -html=cover.out -o cover.html

